#!/bin/bash
#
#  SafeDisk
#  Copyright (C) 2014 Jeremy Bruestle
#  Copyright (C) 2014 Frank Laub
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

error_exit()
{
	echo "$1" 1>&2
	exit 1
}

[[ $# -eq 2 ]] || error_exit "usage: $0 <storage_path> <size in MB>"

storage_path=$1
size_MB=$2

[[ $size_MB -gt 0 && $size_MB -le 1000000 ]] || error_exit "Size in MB is not in range"
[[ -e $storage_path ]] && error_exit "Storage path already exists"
mkdir -p $storage_path/data || error_exit "Unable to create data directory"
mkdir -p $storage_path/fuse_mnt || error_exit "Unable to create fuse mount point"
mkdir -p $storage_path/mnt || error_exit "Unable to create final mount point"
echo $size_MB > $storage_path/size || error_exit "Unable to create size file"

out/release/safedisk -o allow_root $storage_path/fuse_mnt $storage_path/data $size_MB || error_exit "Unable to mnt fuse"
sudo losetup /dev/loop0 $storage/fuse_mnt/data
sudo mkfs /dev/loop0
sudo losetup -d /dev/loop0
