#!/bin/bash

error_exit()
{
	echo "$1" 1>&2
	exit 1
}

[[ $# -eq 2 ]] || error_exit "usage: $0 <storage_path> <size in MB>"

storage_path=$1
size_MB=$2

[[ $size_MB -gt 0 && $size_MB -le 1000000 ]] || error_exit "Size in MB is not in range"
[[ -e $storage_path ]] && error_exit "Storage path already exists"
mkdir -p $storage_path/data || error_exit "Unable to create data directory"
mkdir -p $storage_path/fuse_mnt || error_exit "Unable to create fuse mount point"
mkdir -p $storage_path/mnt || error_exit "Unable to create final mount point"
echo $size_MB > $storage_path/size || error_exit "Unable to create size file"

out/release/safedisk -o allow_root $storage_path/fuse_mnt $storage_path/data $size_MB || error_exit "Unable to mnt fuse"
sudo losetup /dev/loop0 $storage/fuse_mnt/data
sudo mkfs /dev/loop0
sudo losetup -d /dev/loop0
