language: cpp
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
script: ./build
branches:
  only:
    - master
notifications:
  recipients:
    - frank.laub@gmail.com
  email:
    on_success: change
    on_failure: always
env:
  - LANG="en_US.UTF-8"
os:
  - linux
  - osx
