#!/bin/bash -x

set -e

build_linux() {
	sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
	sudo apt-get update -qq
	sudo apt-get install -qq gcc-4.8 g++-4.8 libboost-dev libfuse-dev
	sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
	./build
}

build_osx() {
	brew update
	brew install openssl osxfuse
	source ./osx.env
	./build
}

build_() {
	echo Missing environment variable: TRAVIS_OS_NAME
}

build_${TRAVIS_OS_NAME}
