#!/bin/bash -x

set -e

build_linux() {
	sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
	sudo apt-add-repository -y ppa:beineri/opt-qt532
	sudo apt-get update -qq
	sudo apt-get install -qq gcc-4.8 g++-4.8 libboost-dev libfuse-dev qt53declarative gdb
	sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
	source /opt/qt53/bin/qt53-env.sh
	./build
}

build_osx() {
	brew update
	brew install openssl osxfuse
	source ./osx.env
	./build
}

build_() {
	build_linux
}

build_${TRAVIS_OS_NAME}
