#!/bin/bash
#
#  SafeDisk
#  Copyright (C) 2014 Jeremy Bruestle
#  Copyright (C) 2014 Frank Laub
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

function error_exit
{
	echo "$1" 1>&2
	exit 1
}

[[ $# -eq 1 ]] || error_exit "usage: make_safedisk <storage_path>"

storage_path=$1
size_MB=`cat $storage_path/size`

[[ $size_MB -gt 0 && $size_MB -le 1000000 ]] || error_exit "Size in MB is not in range"

out/release/safedisk $storage_path/fuse_mnt $storage_path/data $size_MB || error_exit "Unable to mnt fuse"

# Kick of hdiutil
hdiutil attach -imagekey diskimage-class=CRawDiskImage $storage_path/fuse_mnt/data
hdiret=$#
# Either way, set off shutdown switch
touch $storage_path/fuse_mnt/shutdown

[[ $hdiret -eq 1 ]] || error_exit "Unable to do hdiutil mount"

